#!/bin/bash

yum install -y libffi libffi-devel zlib-devel
yum remove -y cmake

python3 -m pip install pip --upgrade
python3 -m pip install cmake numpy

bash -c "$(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/main/install)"
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/elapsed || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/almosthere || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s limix/bgen || exit 1
