#!/bin/bash

python3 -m pip install cmake
python3 -m pip install numpy --prefer-binary

bash -c "$(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/main/install)"
bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/almosthere
bash -c "$(curl -fsSL https://git.io/JerYI)" -s limix/bgen
